### ISSUE TITLE
Copied code from Grassmann.jl with no acknowledge

### ISSUE THREAD

**Issue by chakravala** [brainandforce/CliffordNumbers.jl#13]
Cool that you were inspired by my package and copied code from me and took inspiration from my designs and you even learned about the Hodge complement from me too, something I have been trying to convince people of. You should consider putting acknowledgements when you copy pieces of code and take direct inspiration from other other people's project.

**Comment by medav** [comment]
Those are some big claims to have zero concrete evidence of.

> copied code from me
Where? what exact code was copied? If this were true, I feel like you could have _easily_ pointed this out.

> took inspiration from my designs
Evidence?

> you even learned about the Hodge complement from me too
Do you know brainandforce? How could you _possibly_ know this?

The first complaint you raise could be easily proven with a link so please provide that.

The latter two are wild speculation.

**Comment by chakravala** [comment]
> Where? what exact code was copied? If this were true, I feel like you could have easily pointed this out.

I didn't point it out specifically yet, because I a talking to brain and force, who knows that they copied my code, since that's the person who did the act. For example, some of the bit index pieces of code were obviously copied from me, which several people have copied who make geometric algebra Julia packages .. it's always very obvious you copied the code and modified it, since I am the one who originally came up with that piece of code and others took inspiration from it.

>  took inspiration from my designs

Yes, obviously the whole design with using the type parameters in the same exact way that I designed them is an imitation of my original designs. While the signature type is a different implementation, the type parameter design is just a copy of mine.

> The latter two are wild speculation.

No, it's not wild speculation that you copied the Hodge complement idea from me .... because I was the person who has been telling the geometric algebra community to use that definition.

The geometric algebra community laughed at me and mocked me for saying they should use the Hodge complement instead of whatever stupid definitions they use at Cambridge and all those other geometric algebra people with wrong definitions.

In fact, I was the one who had spent years on the chat forums telling people that the Hodge complement is the right way to do it and that everyone else is doing it wrong. People mocked me and made fun of me, so I remember that very well.

I had to go through all of that and I can easily see that you took and copied from me.

Now, for you to claim that this is just speculation and to gaslight me, you are NEVER going to get ANY respect from me for that.

Author here knows they copied ideas from me, took inspiration from me, and has intentionally chosen not to acknowledge that.

I don't need to prove anything, everyone knows that the other GA projects in the Julia community took inspiration from me ... literally everyone knows that ... and it's even more obvious when you actually copied some pieces of code to modify and are directly imitating my design choices and even adopting the same exact definitions I have been begging people to use.

Don't gaslight people ... it's pathetic. Just admit that you took inspiration. I'm not necessarily gonna go after you for GPL violations for this, I just want my acknowledgement ... but if you can't do that ... then we'll see

**Comment by chakravala** [comment]
Other libraries have copied and took inspiration from me also, and those people probably hate me too. but they still put me in the acknowledge because everyone knows where you took the inspiration from.

**Comment by chakravala** [comment]
brain and force basically copied my exact exponential function algorithms, copied and pasted it, and modified it for his copy cat imitation library, which uses the same type parameter design imitated from my project, happens to use the same code I wrote for some of the bit indices, and so on... just happens to chose the same definitions I used, even though the Hodge complement was not the commonly used definition in other geometric algebra projects. it was MY project that used the Hodge complement for geometric algebra, it was ME who vehemently told people to use that definition.

It was not YOU who went through all that experience and all those trials and tribulations leading up to those design choices.

all you did was copy and imitate my project

it's all just a random co-incidence though, so go ahead with the gas-lighting

plagiarism in academia is a common thing now, so if you are gambling with plagiarism, then you probably calculated that it's worth the potential legal costs and that the academic community will ignore issues of plagiarism.

if you would just simply acknowledge where you took your inspiration from, then I would not bother with writing this

**Comment by medav** [comment]
If you feel there's a violation of the GPL here, then I suggest you quit complaining and find a lawyer.

**Comment by chakravala** [comment]
> If you feel there's a violation of the GPL here, then I suggest you quit complaining and find a lawyer.

I'm ready to take immediate action, waiting for the author brainandforce to respond, you have no part in this discussion

**Comment by brainandforce** [comment]
@chakravala, if you see this: **do not attempt to personally contact me again on any platform, for any reason.**

Like many geometric algebra libraries, much of this code was written based on [Geometric Algebra for Computer Science](https://geometricalgebra.org/) by Dorst, Fontijne, and Mann, a work I assume you are familiar with. It was initially published in 2007, well before Julia existed, and describes several implementation details (`BitIndex`, Taylor series exponentials, etc.) which you claim I have copied from your repository. They came from this reference.

You are correct that I should include acknowledgements from contributors, but this does not include you. You have not provided any evidence that my code originated from your repository, which you easily could have done with permalinks to similar/identical code from both of our repositories. Your ideas and opinions alone do not fall under the protection of copyright law.

I will reiterate what @medav stated:
> If you feel there's a violation of the GPL here, then I suggest you quit complaining and find a lawyer.
