### ISSUE TITLE
`CliffordNumbers.regressive` is not exported

### ISSUE THREAD

**Issue by ajahraus** [brainandforce/CliffordNumbers.jl#14]
`CliffordNumbers.regressive` is not exported, but no note about why it is not exported is made in the docs. I suspect this is a simple oversite 😉 

Additionally, although one can access `CliffordNumbers.regressive`, it's infix operator is not accessible is the same way (although it does appear to be in the package when, in the REPL, you enter `CliffordNumbers.<tab>`)

![image](https://github.com/brainandforce/CliffordNumbers.jl/assets/9949357/be4db862-2b13-4dec-abb4-66cebafba228)

**Comment by brainandforce** [comment]
Fixed with #15, thanks!
